### ISSUE TITLE
Arm Rotation

### ISSUE THREAD

**Issue by bot190** [chopshop-166/frc-2024#2]
- [x] Manual rotation - Mapped to joystick
- [x] Preset Amp
- [x] Preset Intake
- [x] Preset Shoot
- [x] Stowed - Default state unless intaking

Soft-stops at ground and full rotation

Sensors:
 - Absolute Encoder

**Comment by msoucy** [comment]
Next steps:
- Find preliminary soft/hard limit values
- Use cslib `ValueRange` for limits

**Comment by Liammurray19** [comment]
Not doing "stowed - default state unless intaking," we don't wanna do it.
