### ISSUE TITLE
Rotate to incorrect angle

### ISSUE THREAD

**Issue by Liammurray19** [chopshop-166/frc-2024#47]
When running the rotate to target angle command the robot rotates not to the target but to the same spot every time, depending on robot to camera transform

Steps to reproduce
- Deploy code
- Enable the robot
- Reset gyro to be parallel with the tag
- Rotate the robot so it can still see the tag
- Let robot sit for enough time estimators get accurate angles (3-5 seconds)
- Run rotate to speaker command

Expected result
- Robot rotates so the center of the robot is facing the center of the tag

Actual result
- Robot rotates to an unknown angle with the tag still in sight, (without deploying anything or resetting gyro) the robot will always rotate to that angle

**Comment by Liammurray19** [comment]
What could be causing it
- [ ] Standard deviation values
- [x] KRobotToCam values
- [ ] ResetGyro makes things funny
- [ ] Check PID position error

**Comment by msoucy** [comment]
Are we sure that the robot to camera translation uses the right coordinate frame? I think I remember seeing that positive X is forward on the robot
